import "./css/globals.scss";
import { Montserrat } from "next/font/google"

import StoreProvider from "../store/StoreProvider";
import Footer from "@/components/footer/Footer";

const font = Montserrat({ subsets: ["latin"], weight: "300" });

export const metadata = {
  title: "Fcore Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={font.className}>
        
        <StoreProvider>{children}</StoreProvider>
        <Footer />
      </body>
    </html>
  );
}
