import localFont from "next/font/local";
import "./globals.scss";

import StoreProvider from "./StoreProvider";

const Montserrat = localFont({
  src: "./fonts/Montserrat-Regular.ttf",
  variable: "--font-montserrat-regular",
  weight: "100 900",
});

export const metadata = {
  title: "Fcore Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Montserrat.variable} ${Montserrat.variable}`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
